# Site settings
title: 3-hour Project Night
description: 'Jekyll-Uno - a minimal, responsive theme for Jekyll'
url: 'http://lqb2.github.io/3h-project-night/'
baseurl: '/3h-project-night/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Josh Gerdes'
  email: josh@joshgerdes.com
  twitter_username: lqb2
  facebook_username: lqbii
  github_username:  lqb2
  linkedin_username:  lawrencebarrinerii

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
